### PR TITLE
chore(deps): use bun 🍞  & upgrade astro v4

### PR DESCRIPTION
**Pull request by hendriknielaender**

### CODE REVIEW

**Comment by flyck** [comment]
When I start it locally the images are broke (i am on the train). Is it the same for you?
image

**Comment by flyck** [comment]
Other people have the same issue and bun is not officially supported by astro:
https://github.com/withastro/astro/issues/9367#issuecomment-1846184495

**Comment by hendriknielaender** [comment]
> When I start it locally the images are broke (i am on the train). Is it the same for you? image

I have no issues 🤷

**Review by flyck — COMMENTED** [review]
Seems cool but as long as bun breaks my local dev setup this MR belongs in the garbaaage 🗑️ 💩

**Comment by hendriknielaender** [comment]
> Seems cool but as long as bun breaks my local dev setup this MR belongs in the garbaaage 🗑️ 💩

@flyck Please try again, if this fixed it.

https://github.com/withastro/astro/issues/9367#issuecomment-1846056427

https://bun.sh/guides/install/trusted

**Comment by flyck** [comment]
```sh
rm -rf node_modules
bun install
bun dev
```

quickly flashes the not working images and then gives me:
```
Expected ")" but found "}"
blog/SinglePost.astro:48:128
```

i guess this is not the fix for us

**Comment by hendriknielaender** [comment]
> ```sh
> rm -rf node_modules
> bun install
> bun dev
> ```
> 
> quickly flashes the not working images and then gives me:
> ```
> Expected ")" but found "}"
> blog/SinglePost.astro:48:128
> ```
> 
> i guess this is not the fix for us

Which bun version are you using? 1.0.21?

**Comment by flyck** [comment]
> Which bun version are you using? 1.0.21?
I was using bun 1.0.0, but same behaviour with bun 1.0.21

**Comment by hendriknielaender** [comment]
> `Expected ")" but found "}"`

Could reproduce the error on single post page, but fixed it.

**Pull request merged**
