### PR TITLE
ci: add automatic posts to medium as draft [#3]

### PR DESCRIPTION
**Pull request by flyck**
can be merged once we confirmed it to work

### CODE REVIEW

**Comment by flyck** [comment]
@hendriknielaender added the medium api key to our bitwarden vault. Since the github permission system is shit also I will give you the honors of adding it as a secret 😄

**Comment by flyck** [comment]
@hendriknielaender ping on this one, please add the secret from the vault, then this one should work 8)

**Comment by hendriknielaender** [comment]
mhh should we post the full post or should we just post an excerpt from it and then link back to the blog? are we allowed to this kind of stuff? @flyck

**Comment by flyck** [comment]
Seems to be legal, but is not recommended for everyone.

Reading a few posts, it is recommended to post different content, which fits the market audience of each different platform. But our audience is the same across dev.to / medium / our own blog. If we wanted to post to reddit, I would for sure only post the link there, not the text.

I suppose cross-posting it is a good way to grow an audience in the very beginning. Once we have a few readers, it might be beneficial to turn off cross-posting again. Though we only want people to read our posts, it doesn't really matter where, on medium or somewhere else. At the moment I dont see the drawback and it is a common practice 🤔 

https://blog.hubspot.com/marketing/cross-posting

**Comment by hendriknielaender** [comment]
added the secret key! ✅

**Comment by flyck** [comment]
No worky worky :( must be because the github action uses deprecated keywords:

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by flyck** [comment]
Turned out unimportant

**Pull request closed without merging**
